# Generated by Django 5.1.3 on 2024-11-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='last_notification_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emi',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emi',
            name='remind_before_days',
            field=models.IntegerField(default=5),
        ),
    ]
